### ISSUE TITLE
Create login

### ISSUE THREAD

**Issue by caiohsramos** [caiohsramos/rails-ss#11]
Create authorization page to block access from unauthorized users. The credentials should be passed as ENV vars during startup and checked in the login page. After login, the user token should be stored in the session and used to make authenticated requests

**Comment by QuangHuy1902** [comment]
Can you assign me and describe what do you want to do for the login form.

**Comment by caiohsramos** [comment]
Hey @QuangHuy1902, added some description to the issue. Feel free to work on this issue and open a pull request.

Some more context: this is meant to be a self-hosted app, so we just need to support 1 user, and it's not supposed to be linked to feeds and items (yet)
